[google]
type = "service_account"
project_id = "barberia-service-account"
private_key_id = "cb6270b56ebe61e66423c6dde937647b46799a74"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDEs1tb4elnjVAf
1AztrMVhXR1Cz/Q0/KLomuWeGkwOYtABXVF/qyEnTnQLn40Dlc8PPLBcMx0hplcB
dt956A6s1vutViz2rfQGo3JPj0/Ww69J6jgiLLdrX0ENaTuQ0mk9/BOpgmJfXz0R
DIwh/NPFAK0TPiUKgwLyQqm+OXbojXZGRuhjkT3pSnLFsIYvLEjkN1QWWUW40iJ5
9QOE0oDWSuTP29kFzlzb2LbySWIRMQlA+orVY6wBDOw60e2Bkm/ax/tiGeKYqDLc
2RKMIVWoXll/lHf5QbTLXvmQYW5u5WWrO5NtMyjm7PpSp3UBjf0XqZHWXwUgHa4o
dn3fLJADAgMBAAECggEAYRK+2IaSILedvkdxJe6o7lb8tNdaBrhTUYX4IeGKfWMI
klPSf7Ydw381R/MyrX1GVZe21ZmoG84yjBd1TH1YmLX0OOQZhpfsoUYSiO8KEMw7
+rdrgnoc/xFgUlUHv34H0D5SGcqt77FZuss9cRyMCmI+CAwYTarATnzVtno3k6Y1
gBfbk6sf3P+amK0bkx03S8Qs2VBTkVfe23hc0RswsqOr5J0DN6o9Pt8djwzulEmp
OhMjTRm0KY7iBU1CC7ikEaVSXl4BXV/7LHEPfYBhE1eSdhB/4Fd8rJoXJniUSjU8
csGqvmkWAdVEmbldej5NEpDXH8aIw0eGoEy/xeAiEQKBgQD9gTA6bGKeIZNWKF/L
nPWz8JAi0YnzxxLT/St6S3s9kpVMZDEdlzB69h8O3BG+xrwak7WcvPzUA86KdLpN
u7i6VHwbnVmUA80l0Tv4hxm1YLX5MRFMy0Xtou5+AAnWZT7ip9VjRG/R4pMzW5l9
rv5Kcp/TS2Iy2kM8QfvdBaaK+wKBgQDGowbeIAjdV+DX/OSrRv07t2YwNEwkofWC
DVD6XAx9Ywjd15lJ2iP7U/DimizMCU4gzj2tQqce4hwzHtGqzIBredvLmmr/3r+1
KPYTlIZV1w0xcaPh6wzPrpBJqYfEd5iDOBjupRRzfxK0HHhD3X1tWTgtVZ5NXOx3
7tuzApKAmQKBgBfumUn6r3i0PL+WgiyrvbpmDIVs+LQN6CYhMXiTJahTbUrP7p8X
hdkl4Rq7BeXXxyxPI4cPhGLTlS0XBfuOrErS7QCCY1GI5lYaoam9v1yTK7rBuhtg
2VIs3o0Ane0ik8Q8CfYcIN5UoIbpr9zgp1sJ5TLCXBvm5RAMPqXIAcf/AoGAdoSJ
MXmNsHuhlV24FpXZvIq19ycNE4JrGPjXCzpm3V18ydi9BnqYo3m3LY1uEyOuMRa9
aCZvzpZ82ueVlEJGkVn5EeeF1jtSyUWyZYZmDMuufITgkoiLcVMnljwH3Oq63fhX
r/RhWnREdaDTBTMfhmIIicwfEuvRz9F91rY/MWkCgYAo+4o57gupTo+ovPr2avaA
NamgAGDEQx4KV+kYNepLmgLDZa9wHtgFzPIF2Eqh+PuuCsMmWw6UM8kl05UmdT4u
5enaGMupGxuTkVq2D/gF0q2rYE0s3IYq4lNmdHOZA13EEhJ5MHO16uu/PqeRG8AO
qspU4/9YWHNI7tR55vG9Xg==
-----END PRIVATE KEY-----"""
client_email = "barberia-service-account@barberiaapp-478106.iam.gserviceaccount.com"
client_id = "106200147850566032060"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/barberia-service-account@barberiaapp-478106.iam.gserviceaccount.com"

calendar_id = "lucky.bvrber5@gmail.com"
sheet_id = "1z4E18eS62VUacbIHb2whKzLYTsS5zyYnRNZTqFFiQgc"
timezone = "America/Santiago"
